# Generated by Django 4.1.3 on 2022-11-27 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LessonDir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=400)),
                ("number", models.IntegerField(unique=True)),
                ("class_date", models.DateField()),
                ("title", models.CharField(default="", max_length=400)),
                ("path", models.FilePathField(allow_folders=True, recursive=True)),
                ("description", models.TextField(max_length=1000, null=True)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
