# Generated by Django 4.1.3 on 2022-11-27 15:46

import apps.lessons.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LessonDir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=400)),
                ("dir_name", models.CharField(max_length=100, unique=True)),
                ("number", models.IntegerField(unique=True)),
                ("class_date", models.DateField()),
                ("title", models.CharField(default="", max_length=400)),
                ("path", models.FilePathField(allow_folders=True, recursive=True)),
                ("description", models.TextField(max_length=1000, null=True)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson_file",
                    models.FileField(upload_to=apps.lessons.models.lesson_file_upload),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "lesson_dir",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessons.lessondir",
                    ),
                ),
            ],
        ),
    ]
