# Generated by Django 4.1.3 on 2022-12-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonquiznotion",
            name="filepath",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="lessonquiznotion",
            name="mongodb_inserted_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="lessonquiznotion",
            name="notion_url",
            field=models.URLField(unique=True),
        ),
    ]
