# Generated by Django 4.1.3 on 2022-12-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_alter_lessonquiznotion_filepath_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonquiznotion",
            name="notion_url",
            field=models.URLField(),
        ),
    ]
